---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      jkube.io/git-url: https://github.com/takealot38-github/spinnaker_poc/
      jkube.io/git-commit: e4d7e8ddd04f874e694bde29bc9e420285310bd2
      jkube.io/git-branch: e4d7e8ddd04f874e694bde29bc9e420285310bd2
      jkube.io/scm-url: https://github.com/spring-projects/spring-boot/spring-boot-starter-parent/hello-svc
      jkube.io/scm-tag: HEAD
      prometheus.io/path: /metrics
      prometheus.io/port: "9779"
      prometheus.io/scrape: "true"
    labels:
      expose: "true"
      app: hello-svc
      provider: jkube
      version: 1.0.18
      group: prmgmdpc-spinnakerpoc
    name: hello-svc
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: hello-svc
      provider: jkube
      group: prmgmdpc-spinnakerpoc
    type: NodePort
- apiVersion: v1
  kind: ConfigMap
  metadata:
    labels:
      app: hello-svc
      provider: jkube
      version: 1.0.18
      group: prmgmdpc-spinnakerpoc
    name: hello-svc
  data:
    application.properties: |
      my_name: Kubelet12
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      configmap.jkube.io/update-on-change: hello-svc
      jkube.io/git-url: https://github.com/takealot38-github/spinnaker_poc/
      jkube.io/git-commit: e4d7e8ddd04f874e694bde29bc9e420285310bd2
      jkube.io/git-branch: e4d7e8ddd04f874e694bde29bc9e420285310bd2
      jkube.io/scm-url: https://github.com/spring-projects/spring-boot/spring-boot-starter-parent/hello-svc
      jkube.io/scm-tag: HEAD
    labels:
      app: hello-svc
      provider: jkube
      version: 1.0.18
      group: prmgmdpc-spinnakerpoc
    name: hello-svc
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      matchLabels:
        app: hello-svc
        provider: jkube
        group: prmgmdpc-spinnakerpoc
    template:
      metadata:
        annotations:
          jkube.io/git-branch: e4d7e8ddd04f874e694bde29bc9e420285310bd2
          jkube.io/scm-url: https://github.com/spring-projects/spring-boot/spring-boot-starter-parent/hello-svc
          jkube.io/git-url: https://github.com/takealot38-github/spinnaker_poc/
          jkube.io/scm-tag: HEAD
          jkube.io/git-commit: e4d7e8ddd04f874e694bde29bc9e420285310bd2
          configmap.jkube.io/update-on-change: hello-svc
        labels:
          app: hello-svc
          provider: jkube
          version: 1.0.18
          group: prmgmdpc-spinnakerpoc
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          image: 172.17.209.204:443/spinnaker_poc/hello-svc:e4d7e8ddd04f874e694bde29bc9e420285310bd2
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 180
            successThreshold: 1
          name: spring-boot
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 9779
            name: prometheus
            protocol: TCP
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            successThreshold: 1
          securityContext:
            privileged: false
          volumeMounts:
          - mountPath: /deployments/config
            name: config
        volumes:
        - configMap:
            items:
            - key: application.properties
              path: application.properties
            name: hello-svc
          name: config
