---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      jkube.io/git-url: https://github.com/takealot38-github/spinnaker_poc
      jkube.io/git-commit: 491973bf6d71e6b6f1e0126aca6fe16a942f133b
      jkube.io/git-branch: 491973bf6d71e6b6f1e0126aca6fe16a942f133b
      jkube.io/scm-url: https://github.com/spring-projects/spring-boot/spring-boot-starter-parent/books-svc
      jkube.io/scm-tag: HEAD
      prometheus.io/path: /metrics
      prometheus.io/port: "9779"
      prometheus.io/scrape: "true"
    labels:
      app: books-svc
      provider: jkube
      version: 0.0.1
      group: prmgmdpc-spinnakerpoc
    name: books-svc
  spec:
    ports:
    - name: sunproxyadmin
      port: 8081
      protocol: TCP
      targetPort: 8081
    selector:
      app: books-svc
      provider: jkube
      group: prmgmdpc-spinnakerpoc
    type: NodePort
- apiVersion: v1
  kind: ConfigMap
  metadata:
    labels:
      app: books-svc
      provider: jkube
      version: 0.0.1
      group: prmgmdpc-spinnakerpoc
    name: books-svc
  data:
    application.properties: |
      my_name: Kubelet11
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      configmap.jkube.io/update-on-change: books-svc
      jkube.io/git-url: https://github.com/takealot38-github/spinnaker_poc
      jkube.io/git-commit: 491973bf6d71e6b6f1e0126aca6fe16a942f133b
      jkube.io/git-branch: 491973bf6d71e6b6f1e0126aca6fe16a942f133b
      jkube.io/scm-url: https://github.com/spring-projects/spring-boot/spring-boot-starter-parent/books-svc
      jkube.io/scm-tag: HEAD
    labels:
      app: books-svc
      provider: jkube
      version: 0.0.1
      group: prmgmdpc-spinnakerpoc
    name: books-svc
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      matchLabels:
        app: books-svc
        provider: jkube
        group: prmgmdpc-spinnakerpoc
    template:
      metadata:
        annotations:
          jkube.io/git-branch: 491973bf6d71e6b6f1e0126aca6fe16a942f133b
          jkube.io/scm-url: https://github.com/spring-projects/spring-boot/spring-boot-starter-parent/books-svc
          jkube.io/git-url: https://github.com/takealot38-github/spinnaker_poc
          jkube.io/scm-tag: HEAD
          jkube.io/git-commit: 491973bf6d71e6b6f1e0126aca6fe16a942f133b
          configmap.jkube.io/update-on-change: books-svc
        labels:
          app: books-svc
          provider: jkube
          version: 0.0.1
          group: prmgmdpc-spinnakerpoc
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          image: 172.17.209.204:443/spinnaker_poc/hello-svc:491973bf6d71e6b6f1e0126aca6fe16a942f133b
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 180
            successThreshold: 1
          name: spring-boot
          ports:
          - containerPort: 8081
            name: sunproxyadmin
            protocol: TCP
          - containerPort: 9779
            name: prometheus
            protocol: TCP
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 10
            successThreshold: 1
          securityContext:
            privileged: false
          volumeMounts:
          - mountPath: /deployments/config
            name: config
        volumes:
        - configMap:
            items:
            - key: application.properties
              path: application.properties
            name: books-svc
          name: config
