---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      prometheus.io/path: /metrics
      prometheus.io/port: "9779"
      prometheus.io/scrape: "true"
    labels:
      expose: "true"
      app: demo-graphql
      provider: jkube
      version: 0.0.1-SNAPSHOT
      group: prmgmdpc-spinnakerpoc
    name: demo-graphql
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: demo-graphql
      provider: jkube
      group: prmgmdpc-spinnakerpoc
    type: NodePort
- apiVersion: v1
  kind: ConfigMap
  metadata:
    labels:
      app: demo-graphql
      provider: jkube
      version: 0.0.1-SNAPSHOT
      group: prmgmdpc-spinnakerpoc
    name: demo-graphql
  data:
    books_svc: books-svc
    authors_svc: authors-svc
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
    labels:
      app: demo-graphql
      provider: jkube
      version: 0.0.1-SNAPSHOT
      group: prmgmdpc-spinnakerpoc
    name: demo-graphql
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      matchLabels:
        app: demo-graphql
        provider: jkube
        group: prmgmdpc-spinnakerpoc
    template:
      metadata:
        annotations:
        labels:
          app: demo-graphql
          provider: jkube
          version: 0.0.1-SNAPSHOT
          group: prmgmdpc-spinnakerpoc
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          image: 172.17.100.220:443/rbuhrmann/graphql-poc:latest
          imagePullPolicy: IfNotPresent
          name: spring-boot
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 9779
            name: prometheus
            protocol: TCP
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          securityContext:
            privileged: false
          volumeMounts:
          - mountPath: /deployments/config
            name: config
        volumes:
        - configMap:
            items:
            - key: books_svc
              path: books_svc
            - key: authors_svc
              path: authors_svc
            name: demo-graphql
          name: config
