---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      jkube.io/git-url: https://github.com/takealot38-github/spinnaker_poc
      jkube.io/git-commit: b57f0db046751e94f25ee52d717a8e28cb3b638f
      jkube.io/git-branch: b57f0db046751e94f25ee52d717a8e28cb3b638f
      jkube.io/scm-url: https://github.com/spring-projects/spring-boot/spring-boot-starter-parent/authors-svc
      jkube.io/scm-tag: HEAD
      prometheus.io/path: /metrics
      prometheus.io/port: "9779"
      prometheus.io/scrape: "true"
    labels:
      app: authors-svc
      provider: jkube
      version: 0.0.1
      group: prmgmdpc-spinnakerpoc
    name: authors-svc
  spec:
    ports:
    - name: us-cli
      port: 8082
      protocol: TCP
      targetPort: 8082
    selector:
      app: authors-svc
      provider: jkube
      group: prmgmdpc-spinnakerpoc
- apiVersion: v1
  kind: ConfigMap
  metadata:
    labels:
      app: authors-svc
      provider: jkube
      version: 0.0.1
      group: prmgmdpc-spinnakerpoc
    name: authors-svc
  data:
    application.properties: |
      my_name: Kubelet11
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      configmap.jkube.io/update-on-change: authors-svc
      jkube.io/git-url: https://github.com/takealot38-github/spinnaker_poc
      jkube.io/git-commit: b57f0db046751e94f25ee52d717a8e28cb3b638f
      jkube.io/git-branch: b57f0db046751e94f25ee52d717a8e28cb3b638f
      jkube.io/scm-url: https://github.com/spring-projects/spring-boot/spring-boot-starter-parent/authors-svc
      jkube.io/scm-tag: HEAD
    labels:
      app: authors-svc
      provider: jkube
      version: 0.0.1
      group: prmgmdpc-spinnakerpoc
    name: authors-svc
  spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
      matchLabels:
        app: authors-svc
        provider: jkube
        group: prmgmdpc-spinnakerpoc
    template:
      metadata:
        annotations:
          jkube.io/git-branch: b57f0db046751e94f25ee52d717a8e28cb3b638f
          jkube.io/scm-url: https://github.com/spring-projects/spring-boot/spring-boot-starter-parent/authors-svc
          jkube.io/git-url: https://github.com/takealot38-github/spinnaker_poc
          jkube.io/scm-tag: HEAD
          jkube.io/git-commit: b57f0db046751e94f25ee52d717a8e28cb3b638f
          configmap.jkube.io/update-on-change: authors-svc
        labels:
          app: authors-svc
          provider: jkube
          version: 0.0.1
          group: prmgmdpc-spinnakerpoc
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          image: 172.17.100.220:443/spinnaker_poc/authors-svc:b57f0db046751e94f25ee52d717a8e28cb3b638f
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8082
              scheme: HTTP
            initialDelaySeconds: 180
            successThreshold: 1
          name: spring-boot
          ports:
          - containerPort: 8082
            name: us-cli
            protocol: TCP
          - containerPort: 9779
            name: prometheus
            protocol: TCP
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8082
              scheme: HTTP
            initialDelaySeconds: 10
            successThreshold: 1
          securityContext:
            privileged: false
          volumeMounts:
          - mountPath: /deployments/config
            name: config
        volumes:
        - configMap:
            items:
            - key: application.properties
              path: application.properties
            name: authors-svc
          name: config
