---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: Demo_GraphQL
    provider: jkube
    version: 0.0.1-SNAPSHOT
    group: prmgmdpc-spinnakerpoc
  name: demo_graphql
data:
  application.properties: |
    books_svc: books-svc
    authors_svc: authors-svc
