metadata:
  annotations:
    configmap.jkube.io/update-on-change:
spec:
  replicas: 1
  template:
    spec:
      volumes:
        - name: config
          configMap:
            name: ${project.artifactId}
            items:
              - key: my_name
                path: my_name
      containers:
        - volumeMounts:
            - name: config
              mountPath: /deployments/config