metadata:
  annotations:
    configmap.jkube.io/update-on-change: ${project.artifactId}
#    traffic.spinnaker.io/load-balancers: '["service ${project.artifactId}"]'  # used to define replicaset that can be turned into server group on spinnaker
spec:
  replicas: 2
#  selector:
#    matchLabels:
#      tier: forreplicaset                                                      # used to define replicaset that can be turned into server group on spinnaker
  template:
    spec:
      volumes:
        - name: config
          configMap:
            name: ${project.artifactId}
            items:
              - key: my_name
                path: my_name
      containers:
        - volumeMounts:
            - name: config
              mountPath: /deployments/config
